
package GUI;
import DTO.DocGiaDTO;
import BUS.DocGiaBUS;
import DAO.DocGiaDAO;
import DAO.DAO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
public class QuanLyDocGia extends javax.swing.JFrame {
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/mm/yyyy");
    private DefaultTableModel modelDocGia = new DefaultTableModel();
    private DefaultTableModel resOfSearch;
    private int EditOrSearch=1;
    private DocGiaBUS docgiabus=new DocGiaBUS();
    /**
     * Creates new form QuanLyDocGia
     */
    public QuanLyDocGia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btXoa = new javax.swing.JButton();
        btTim = new javax.swing.JButton();
        btTatCa = new javax.swing.JButton();
        btTaoMoi = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txMaDG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txHoDG = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txTenDG = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txNSDG = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txDCDG = new javax.swing.JTextField();
        txDTDG = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txNNDG = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btThem = new javax.swing.JButton();
        btXoa1 = new javax.swing.JButton();
        btSua1 = new javax.swing.JButton();
        btTim1 = new javax.swing.JButton();
        btTatCa1 = new javax.swing.JButton();
        btTaoMoi1 = new javax.swing.JButton();
        btDong = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDocGia = new javax.swing.JTable();
        btXacNhan = new javax.swing.JButton();
        btHuy = new javax.swing.JButton();
        cbTDDG = new javax.swing.JComboBox<>();
        txGTDG = new javax.swing.JTextField();

        btXoa.setBackground(new java.awt.Color(27, 26, 67));
        btXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoa.setForeground(new java.awt.Color(255, 255, 255));
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/minus.png"))); // NOI18N
        btXoa.setText("Xoá");
        btXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btTim.setBackground(new java.awt.Color(27, 26, 67));
        btTim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTim.setForeground(new java.awt.Color(255, 255, 255));
        btTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/search.png"))); // NOI18N
        btTim.setText("Tìm kiếm");
        btTim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTim.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        btTatCa.setBackground(new java.awt.Color(165, 201, 63));
        btTatCa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTatCa.setForeground(new java.awt.Color(255, 255, 255));
        btTatCa.setText("Tất cả");
        btTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTatCaActionPerformed(evt);
            }
        });

        btTaoMoi.setBackground(new java.awt.Color(255, 153, 51));
        btTaoMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTaoMoi.setForeground(new java.awt.Color(255, 255, 255));
        btTaoMoi.setText("Tạo mới");
        btTaoMoi.setToolTipText("");
        btTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaoMoiActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 29, 65));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ ĐỘC GIẢ");

        jPanel2.setBackground(new java.awt.Color(30, 29, 65));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã độc giả:");

        txMaDG.setBackground(new java.awt.Color(27, 26, 67));
        txMaDG.setForeground(new java.awt.Color(255, 255, 255));
        txMaDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMaDGActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Họ độc giả:");

        txHoDG.setBackground(new java.awt.Color(27, 26, 67));
        txHoDG.setForeground(new java.awt.Color(255, 255, 255));
        txHoDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHoDGActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tên độc giả:");

        txTenDG.setBackground(new java.awt.Color(27, 26, 67));
        txTenDG.setForeground(new java.awt.Color(255, 255, 255));
        txTenDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTenDGActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ngày sinh:");

        txNSDG.setBackground(new java.awt.Color(27, 26, 67));
        txNSDG.setForeground(new java.awt.Color(255, 255, 255));
        txNSDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNSDGActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Địa chỉ:");

        txDCDG.setBackground(new java.awt.Color(27, 26, 67));
        txDCDG.setForeground(new java.awt.Color(255, 255, 255));
        txDCDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDCDGActionPerformed(evt);
            }
        });

        txDTDG.setBackground(new java.awt.Color(27, 26, 67));
        txDTDG.setForeground(new java.awt.Color(255, 255, 255));
        txDTDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDTDGActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Điện thoại:");

        txNNDG.setBackground(new java.awt.Color(27, 26, 67));
        txNNDG.setForeground(new java.awt.Color(255, 255, 255));
        txNNDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNNDGActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nghề nghiệp:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Trình độ:");

        btThem.setBackground(new java.awt.Color(27, 26, 67));
        btThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThem.setForeground(new java.awt.Color(255, 255, 255));
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/add.png"))); // NOI18N
        btThem.setText("Thêm");
        btThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa1.setBackground(new java.awt.Color(27, 26, 67));
        btXoa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoa1.setForeground(new java.awt.Color(255, 255, 255));
        btXoa1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\JAVA\\DoAnJava\\QuanLyThuVien\\QuanLyThuVien\\src\\iconImages\\minus.png")); // NOI18N
        btXoa1.setText("Xoá");
        btXoa1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoa1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoa1ActionPerformed(evt);
            }
        });

        btSua1.setBackground(new java.awt.Color(27, 26, 67));
        btSua1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSua1.setForeground(new java.awt.Color(255, 255, 255));
        btSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/edit.png"))); // NOI18N
        btSua1.setText("Sửa");
        btSua1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSua1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSua1ActionPerformed(evt);
            }
        });

        btTim1.setBackground(new java.awt.Color(27, 26, 67));
        btTim1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTim1.setForeground(new java.awt.Color(255, 255, 255));
        btTim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/search.png"))); // NOI18N
        btTim1.setText("Tìm kiếm");
        btTim1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTim1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTim1ActionPerformed(evt);
            }
        });

        btTatCa1.setBackground(new java.awt.Color(165, 201, 63));
        btTatCa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTatCa1.setForeground(new java.awt.Color(255, 255, 255));
        btTatCa1.setText("Tất cả");
        btTatCa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTatCa1ActionPerformed(evt);
            }
        });

        btTaoMoi1.setBackground(new java.awt.Color(255, 153, 51));
        btTaoMoi1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTaoMoi1.setForeground(new java.awt.Color(255, 255, 255));
        btTaoMoi1.setText("Tạo mới");
        btTaoMoi1.setToolTipText("");
        btTaoMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaoMoi1ActionPerformed(evt);
            }
        });

        btDong.setBackground(new java.awt.Color(206, 81, 80));
        btDong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btDong.setForeground(new java.awt.Color(255, 255, 255));
        btDong.setText("Đóng");
        btDong.setToolTipText("");
        btDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDongActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Giới Tính");

        tbDocGia.setBackground(new java.awt.Color(20, 20, 50));
        tbDocGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbDocGia.setForeground(new java.awt.Color(255, 255, 255));
        tbDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Đọc Giả", "Họ Lót", "Tên ", "Ngày Sinh", "Giới Tính", "Điện Thoại", "Địa Chỉ", "Nghề Nghiệp", "Trình Độ"
            }
        ));
        tbDocGia.setRowHeight(25);
        tbDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDocGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDocGia);

        btXacNhan.setBackground(new java.awt.Color(165, 201, 63));
        btXacNhan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btXacNhan.setText("Xác nhận");
        btXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXacNhanActionPerformed(evt);
            }
        });

        btHuy.setBackground(new java.awt.Color(206, 81, 80));
        btHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btHuy.setForeground(new java.awt.Color(255, 255, 255));
        btHuy.setText("Huỷ");
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });

        cbTDDG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đại Học", "Cao Đẳng", "Khác" }));
        cbTDDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTDDGActionPerformed(evt);
            }
        });

        txGTDG.setBackground(new java.awt.Color(27, 26, 67));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txMaDG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txHoDG, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txDCDG, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btXoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txDTDG, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btTatCa1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btTim1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btSua1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txTenDG, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txNSDG, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(txGTDG))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(btXacNhan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txNNDG, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTDDG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btTaoMoi1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(btDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txDCDG, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(txMaDG))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txHoDG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txDTDG, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txNNDG, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(txTenDG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txNSDG, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(cbTDDG)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTim1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTatCa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTaoMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txGTDG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btXacNhan)
                        .addComponent(btHuy)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btXacNhan.setVisible(false);
        btHuy.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
       
    }//GEN-LAST:event_btTimActionPerformed

    private void btTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTatCaActionPerformed
     
    }//GEN-LAST:event_btTatCaActionPerformed

    private void btTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaoMoiActionPerformed
       
    }//GEN-LAST:event_btTaoMoiActionPerformed

    private void cbTDDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTDDGActionPerformed
    String selectedItem = (String) cbTDDG.getSelectedItem();
    }//GEN-LAST:event_cbTDDGActionPerformed

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        // TODO add your handling code here:
        if(EditOrSearch==1){
            txMaDG.setEditable(true);
            tbDocGia.setEnabled(true);
            btThem.setEnabled(true);
            btXoa1.setEnabled(true);
            btTim1.setEnabled(true);
            btTatCa1.setEnabled(true);
            btXacNhan.setVisible(false);
            btHuy.setVisible(false);
        }
        else{
            txMaDG.setEditable(true);
            tbDocGia.setEnabled(true);
            btThem.setEnabled(true);         
            btTim.setEnabled(true);
            btTatCa.setEnabled(true);
            btXacNhan.setVisible(false);
            btHuy.setVisible(false);
            btXacNhan.setVisible(false);
            btHuy.setVisible(false);
        }
    }//GEN-LAST:event_btHuyActionPerformed

    private void btXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXacNhanActionPerformed
        // TODO add your handling code here:
        Edit();

    }//GEN-LAST:event_btXacNhanActionPerformed

    private void tbDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDocGiaMouseClicked
        int i = tbDocGia.getSelectedRow();
        if (docgiabus.getList().size() > 0) {
            DocGiaDTO docgia = new DocGiaDTO();
            docgia = docgiabus.getList().get(i);
            txMaDG.setText(docgia.getMaDocGia());
            txHoDG.setText(docgia.getHoDocGia());
            txTenDG.setText(docgia.getTenDocGia());
            txNSDG.setText(docgia.getNgaysinh());
            if(docgia.getGioiTinh()==1){
                txGTDG.setText("Nam");
            } else txGTDG.setText("Nữ");
            txDCDG.setText(docgia.getDiachi());
            txDTDG.setText(docgia.getDienthoai());
            txNNDG.setText(docgia.getNghenghiep());
            for(int j=0;j<cbTDDG.getItemCount();j++)
            if(cbTDDG.getItemAt(j).equals(docgia.getTrinhdo()))
            cbTDDG.setSelectedIndex(j);
        }
    }//GEN-LAST:event_tbDocGiaMouseClicked

    private void btDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btDongActionPerformed

    private void btTaoMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaoMoi1ActionPerformed
        // TODO add your handling code here:
        if(tbDocGia.isEnabled())
        txMaDG.setText("");
        txHoDG.setText("");
        txTenDG.setText("");
        txNSDG.setText("");
        txDCDG.setText("");
        txDTDG.setText("");
        txNNDG.setText("");
        cbTDDG.setSelectedIndex(0);
        
    }//GEN-LAST:event_btTaoMoi1ActionPerformed

    private void btTatCa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTatCa1ActionPerformed
        // TODO add your handling code here:
        if (docgiabus.getList().size()>0)
        tbDocGia.setModel(modelDocGia);
    }//GEN-LAST:event_btTatCa1ActionPerformed

    private void btTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTim1ActionPerformed
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_btTim1ActionPerformed

    private void btSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSua1ActionPerformed
        int i=tbDocGia.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Chọn độc giả cần chỉnh sửa", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        EditOrSearch=1;
        txMaDG.setEditable(false);
        tbDocGia.setEnabled(false);
        btThem.setEnabled(false);
        btXoa1.setEnabled(false);
        btTim1.setEnabled(false);
        btTatCa1.setEnabled(false);
        btXacNhan.setText("Sửa");
        btXacNhan.setVisible(true);
        btHuy.setVisible(true);
    }//GEN-LAST:event_btSua1ActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        if(!ValidateThemDocGia())
        return;

        DocGiaDTO docgia=new DocGiaDTO();
        docgia.setMaDocGia(txMaDG.getText());
        docgia.setHoDocGia(txHoDG.getText());
        docgia.setTenDocGia(txTenDG.getText());
        docgia.setNgaysinh(txNSDG.getText());
        if(txGTDG.getText().equals("Nam")){
               docgia.setGioiTinh(1);
            } else if(txGTDG.getText().equals("Nữ")){ 
                docgia.setGioiTinh(0);
            }
        docgia.setDienthoai(txDTDG.getText());
        docgia.setDiachi(txDCDG.getText());
        docgia.setNghenghiep(txNNDG.getText());
        docgia.setTrinhdo(cbTDDG.getSelectedItem().toString());

        try {
            docgiabus.Add(docgia);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }

        Vector row=new Vector();
        row.add(docgia.getMaDocGia());
        row.add(docgia.getHoDocGia());
        row.add(docgia.getTenDocGia());
        row.add(docgia.getNgaysinh());
        if(docgia.getGioiTinh()==1){
            row.add("Nam");
        } else row.add("Nữ");              
        row.add(docgia.getDienthoai());
        row.add(docgia.getDiachi());
        row.add(docgia.getNghenghiep());
        row.add(docgia.getTrinhdo());
        modelDocGia.addRow(row);

        tbDocGia.setModel(modelDocGia);

    }//GEN-LAST:event_btThemActionPerformed

    private void txNNDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNNDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNNDGActionPerformed

    private void txDTDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDTDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDTDGActionPerformed

    private void txDCDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDCDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDCDGActionPerformed

    private void txNSDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNSDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNSDGActionPerformed

    private void txTenDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTenDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTenDGActionPerformed

    private void txHoDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHoDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHoDGActionPerformed

    private void txMaDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMaDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMaDGActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed

    }//GEN-LAST:event_btXoaActionPerformed

    private void btXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoa1ActionPerformed
        int i = tbDocGia.getSelectedRow();
        DocGiaDTO docgia = new DocGiaDTO();
        docgia = docgiabus.getList().get(i);
        if(docgiabus.getList().size()>0){
            try {
                docgiabus.Remove(docgiabus .getList().get(i).getMaDocGia());
            } catch (Exception ex) {
                Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
            }
            modelDocGia.removeRow(i);
            tbDocGia.setModel(modelDocGia);
            txGTDG.setText("");
            if(docgia.getGioiTinh()==1){
                txGTDG.setText("Nam");
            } else txGTDG.setText("Nữ");
            txMaDG.setText("");
            txHoDG.setText("");
            txTenDG.setText("");
            txNSDG.setText("");
            txDTDG.setText("");
            txDCDG.setText("");
            txNNDG.setText("");
            cbTDDG.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btXoa1ActionPerformed
    public void List() throws Exception{
        if(docgiabus.getList()==null)
            docgiabus.listDocGia();
        ArrayList<DocGiaDTO> listMS= docgiabus.getList();
        Vector header=new Vector();
            header.add("Mã Đọc Giả");
            header.add("Họ Lót");
            header.add("Tên");
            header.add("Ngày Sinh");
            header.add("Giới Tính");
            header.add("Điện Thoại");
            header.add("Địa Chỉ");
            header.add("Nghề Nghiệp");
            header.add("Trình Độ");
            
        if (modelDocGia.getRowCount() == 0) 
                modelDocGia = new DefaultTableModel(header, 0);
        for(DocGiaDTO dg: listMS) {
            Vector row=new Vector();
            row.add(dg.getMaDocGia());
            row.add(dg.getHoDocGia());
            row.add(dg.getTenDocGia());
            row.add(dg.getNgaysinh());
            if(dg.getGioiTinh()==1){
               row.add("Nam");
            } else row.add("Nữ");
           
            row.add(dg.getDienthoai());
            row.add(dg.getDiachi());
            row.add(dg.getNghenghiep());
            row.add(dg.getTrinhdo());
            modelDocGia.addRow(row);
        }
        tbDocGia.setModel(modelDocGia);
    }
    private void Edit(){
        int i=tbDocGia.getSelectedRow();
        if(docgiabus.getList().size()>0){
            DocGiaDTO dg=new DocGiaDTO();

            dg.setMaDocGia(txMaDG.getText());
            dg.setHoDocGia(txHoDG.getText());
            dg.setTenDocGia(txTenDG.getText());
            dg.setNgaysinh(txNSDG.getText());
            if(txGTDG.getText().equals("Nam")){
               dg.setGioiTinh(1);
            } else if(txGTDG.getText().equals("Nữ")){ 
                dg.setGioiTinh(0);
            }
            dg.setDienthoai(txDTDG.getText());
            dg.setDiachi(txDCDG.getText());
            dg.setNghenghiep(txNNDG.getText());
            dg.setTrinhdo(cbTDDG.getSelectedItem().toString());

            try {
                docgiabus.Edit(dg);
            } catch (Exception ex) {
                Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
            }

            modelDocGia.setValueAt(dg.getMaDocGia(), i, 0);
            modelDocGia.setValueAt(dg.getHoDocGia(), i, 1);
            modelDocGia.setValueAt(dg.getTenDocGia(), i, 2);
            modelDocGia.setValueAt(dg.getNgaysinh(), i, 3);
            if(dg.getGioiTinh()==1){
                modelDocGia.setValueAt("Nam", i, 4);
            } else modelDocGia.setValueAt("Nữ", i, 4);
            
            modelDocGia.setValueAt(dg.getDienthoai(), i, 5);
            modelDocGia.setValueAt(dg.getDiachi(), i, 6);
            modelDocGia.setValueAt(dg.getNghenghiep(), i, 7);
            modelDocGia.setValueAt(dg.getTrinhdo(), i, 8);

            tbDocGia.setModel(modelDocGia);
        }
        txMaDG.setEditable(true);
        tbDocGia.setEnabled(true);
        btThem.setEnabled(true);
        btXoa1.setEnabled(true);
        btTim1.setEnabled(true);
        btTatCa1.setEnabled(true);
        //btNhapEx.setEnabled(true);
        //btXuatEx.setEnabled(true);
        btXacNhan.setVisible(false);
        btHuy.setVisible(false);
    }
    private void Search(){
        if(docgiabus.getList().isEmpty()){
            return;
        }

        String MaDocGia, HoDocGia, TenDocGia, Ngaysinh, Diachi, Dienthoai, Nghenghiep, Trinhdo = null;
        int GioiTinh;
        MaDocGia=txMaDG.getText();
        HoDocGia=txHoDG.getText();
        TenDocGia=txTenDG.getText();
        Ngaysinh=txNSDG.getText();
        if(txGTDG.getText().equals("Nam")){
            GioiTinh=1;
        } else  if(txGTDG.getText().equals("Nữ")){
            GioiTinh=0;} else GioiTinh=-1;
        Diachi=txDCDG.getText();
        Dienthoai=txDTDG.getText();
        Nghenghiep=txNNDG.getText();
        Trinhdo = cbTDDG.getSelectedItem().toString();
        System.out.print(Trinhdo);

        ArrayList<DocGiaDTO> res=new ArrayList<DocGiaDTO>();
        try {
            res=docgiabus.Search(MaDocGia, HoDocGia, TenDocGia, Ngaysinh, GioiTinh, Dienthoai, Diachi, Nghenghiep, Trinhdo);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (res.size()==0)
            JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả nào!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        else{
            Vector header = new Vector();
            header.add("Mã Đọc Giả");
            header.add("Họ Lót");
            header.add("Tên ");
            header.add("Ngày sinh");
            header.add("Giới Tính");
            header.add("Điện Thoại");
            header.add("Địa Chỉ");
            header.add("Nghề Nghiệp");
            header.add("Trình Độ");
            resOfSearch = new DefaultTableModel(header, 0);
            for(DocGiaDTO d: res){
                Vector row=new Vector();
                row.add(d.getMaDocGia());
                row.add(d.getHoDocGia());
                row.add(d.getTenDocGia());
                row.add(d.getNgaysinh());
                if(d.getGioiTinh()==1){
                    row.add("Nam");
                } else row.add("Nữ");             
                
                row.add(d.getDienthoai());
                row.add(d.getDiachi());
                row.add(d.getNghenghiep());
                row.add(d.getTrinhdo());
                resOfSearch.addRow(row);
            }
            tbDocGia.setModel(resOfSearch);
        }
    }
    
    
    private boolean ValidateThemDocGia(){
        String madocgia, hodocgia, tendocgia, ngaysinh, gioitinh, diachi, dienthoai, nghenghiep, trinhdo;
        int GioiTinh;
        madocgia=txMaDG.getText();
        hodocgia=txHoDG.getText();
        tendocgia=txTenDG.getText();
        ngaysinh=txNSDG.getText();
        diachi=txDCDG.getText();
        dienthoai=txDTDG.getText();
        nghenghiep=txNNDG.getText();
       if(txGTDG.getText().equals("Nam")){
            GioiTinh=1;
        } else  if(txGTDG.getText().equals("Nữ")){
            GioiTinh=0;} else GioiTinh=-1;
//        trinhdo=cbTDDG.getSelectedIndex();
        if(madocgia.equals("") || hodocgia.equals("") || tendocgia.equals("") || ngaysinh.equals("") || diachi.equals("") || dienthoai.equals("") || nghenghiep.equals("") ){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        for(DocGiaDTO docgia: docgiabus.getList()){
            if(madocgia.equals(docgia.getMaDocGia())){
                JOptionPane.showMessageDialog(null, "Mã độc giả đã tồn tại", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
                return false;
            }
        }     
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyDocGia QLDG=new QuanLyDocGia();
                try {
                    QLDG.List();          
                } catch (Exception ex) { 
                    Logger.getLogger(QuanLyDocGia.class.getName()).log(Level.SEVERE, null, ex);
                }
                QLDG.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDong;
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btSua1;
    private javax.swing.JButton btTaoMoi;
    private javax.swing.JButton btTaoMoi1;
    private javax.swing.JButton btTatCa;
    private javax.swing.JButton btTatCa1;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btTim;
    private javax.swing.JButton btTim1;
    private javax.swing.JButton btXacNhan;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btXoa1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTDDG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDocGia;
    private javax.swing.JTextField txDCDG;
    private javax.swing.JTextField txDTDG;
    private javax.swing.JTextField txGTDG;
    private javax.swing.JTextField txHoDG;
    private javax.swing.JTextField txMaDG;
    private javax.swing.JTextField txNNDG;
    private javax.swing.JTextField txNSDG;
    private javax.swing.JTextField txTenDG;
    // End of variables declaration//GEN-END:variables
}
