/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.PhieuMuonBUS;
import DTO.PhieuMuonDTO;
import BUS.ChiTietPhieuMuonBUS;
import DTO.ChiTietPhieuMuonDTO;
import BUS.SachBUS;
import DTO.SachDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.JOptionPane;

/**
 *
 * @author 01042001
 */
public class QuanLyMuonTra extends javax.swing.JFrame {
    private DefaultTableModel modelPhieuMuon = new DefaultTableModel();
    private DefaultTableModel modelChitiet = new DefaultTableModel();
    private DefaultTableModel resOfSearch;
    private int EditOrSearch;
    private PhieuMuonBUS phieumuonbus=new PhieuMuonBUS();
    private ChiTietPhieuMuonBUS chitietbus=new ChiTietPhieuMuonBUS();
    /**
     * Creates new form QuanLyMuonTra
     */
    
    public QuanLyMuonTra() {
        initComponents();
         tbPhieuMuon.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {

            }

            @Override
            public void mousePressed(MouseEvent me) {
                Onclick();
            }

            @Override
            public void mouseReleased(MouseEvent me) {

            }

            @Override
            public void mouseEntered(MouseEvent me) {

            }

            @Override
            public void mouseExited(MouseEvent me) {

            }
        });
         tbChitiet.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {

            }

            @Override
            public void mousePressed(MouseEvent me) {
                Onclickct();
            }

            @Override
            public void mouseReleased(MouseEvent me) {

            }

            @Override
            public void mouseEntered(MouseEvent me) {

            }

            @Override
            public void mouseExited(MouseEvent me) {

            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfMaPhieuMuon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfMaDocGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMaNhanVien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNgayMuon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfNgayHenTra = new javax.swing.JTextField();
        btMaDocGia = new javax.swing.JButton();
        btMaNhanVien = new javax.swing.JButton();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btTim = new javax.swing.JButton();
        btTatCa = new javax.swing.JButton();
        btTaoMoi = new javax.swing.JButton();
        btXacNhan = new javax.swing.JButton();
        btHuy = new javax.swing.JButton();
        btDong = new javax.swing.JButton();
        btChon3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPhieuMuon = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfMaPmChiTiet = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfMaSach = new javax.swing.JTextField();
        btMaSach = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfSoLuong = new javax.swing.JTextField();
        btThem1 = new javax.swing.JButton();
        btXoa1 = new javax.swing.JButton();
        btSua1 = new javax.swing.JButton();
        btTaoMoi1 = new javax.swing.JButton();
        btTimCt = new javax.swing.JButton();
        btAll = new javax.swing.JButton();
        btChon4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChitiet = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 29, 65));

        jPanel2.setBackground(new java.awt.Color(30, 29, 65));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Mượn Trả");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(30, 29, 65));

        jPanel4.setBackground(new java.awt.Color(30, 29, 65));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Mượn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã Phiếu Mượn: ");

        tfMaPhieuMuon.setBackground(new java.awt.Color(27, 26, 67));
        tfMaPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        tfMaPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaPhieuMuonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã Độc Giả: ");

        tfMaDocGia.setBackground(new java.awt.Color(27, 26, 67));
        tfMaDocGia.setForeground(new java.awt.Color(255, 255, 255));
        tfMaDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaDocGiaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã Nhân Viên: ");

        tfMaNhanVien.setBackground(new java.awt.Color(27, 26, 67));
        tfMaNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        tfMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaNhanVienActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ngày Mượn:");

        tfNgayMuon.setBackground(new java.awt.Color(27, 26, 67));
        tfNgayMuon.setForeground(new java.awt.Color(255, 255, 255));
        tfNgayMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNgayMuonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày Hẹn Trả:");

        tfNgayHenTra.setBackground(new java.awt.Color(27, 26, 67));
        tfNgayHenTra.setForeground(new java.awt.Color(255, 255, 255));
        tfNgayHenTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNgayHenTraActionPerformed(evt);
            }
        });

        btMaDocGia.setBackground(new java.awt.Color(27, 26, 67));
        btMaDocGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMaDocGia.setForeground(new java.awt.Color(255, 255, 255));
        btMaDocGia.setText("...");
        btMaDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaDocGiaActionPerformed(evt);
            }
        });

        btMaNhanVien.setBackground(new java.awt.Color(27, 26, 67));
        btMaNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMaNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btMaNhanVien.setText("...");
        btMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaNhanVienActionPerformed(evt);
            }
        });

        btThem.setBackground(new java.awt.Color(27, 26, 67));
        btThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThem.setForeground(new java.awt.Color(255, 255, 255));
        btThem.setText("Thêm");
        btThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setBackground(new java.awt.Color(27, 26, 67));
        btXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoa.setForeground(new java.awt.Color(255, 255, 255));
        btXoa.setText("Xoá");
        btXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btSua.setBackground(new java.awt.Color(27, 26, 67));
        btSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSua.setForeground(new java.awt.Color(255, 255, 255));
        btSua.setText("Sửa");
        btSua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btTim.setBackground(new java.awt.Color(27, 26, 67));
        btTim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTim.setForeground(new java.awt.Color(255, 255, 255));
        btTim.setText("Tìm kiếm");
        btTim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTim.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        btTatCa.setBackground(new java.awt.Color(165, 201, 63));
        btTatCa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTatCa.setForeground(new java.awt.Color(255, 255, 255));
        btTatCa.setText("Tất cả");
        btTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTatCaActionPerformed(evt);
            }
        });

        btTaoMoi.setBackground(new java.awt.Color(255, 153, 51));
        btTaoMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTaoMoi.setForeground(new java.awt.Color(255, 255, 255));
        btTaoMoi.setText("Tạo mới");
        btTaoMoi.setToolTipText("");
        btTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaoMoiActionPerformed(evt);
            }
        });

        btXacNhan.setBackground(new java.awt.Color(165, 201, 63));
        btXacNhan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btXacNhan.setText("Xác nhận");
        btXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXacNhanActionPerformed(evt);
            }
        });

        btHuy.setBackground(new java.awt.Color(206, 81, 80));
        btHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btHuy.setForeground(new java.awt.Color(255, 255, 255));
        btHuy.setText("Huỷ");
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });

        btDong.setBackground(new java.awt.Color(206, 81, 80));
        btDong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btDong.setForeground(new java.awt.Color(255, 255, 255));
        btDong.setText("Đóng");
        btDong.setToolTipText("");
        btDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDongActionPerformed(evt);
            }
        });

        btChon3.setBackground(new java.awt.Color(27, 26, 67));
        btChon3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btChon3.setForeground(new java.awt.Color(255, 255, 255));
        btChon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/select.png"))); // NOI18N
        btChon3.setText("Chọn");
        btChon3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btChon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChon3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNgayHenTra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btXacNhan)
                        .addGap(30, 30, 30)
                        .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tfMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMaDocGia))
                    .addComponent(tfMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMaNhanVien))
                    .addComponent(tfNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTaoMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTim, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(btTatCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btChon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMaDocGia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btMaNhanVien))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(tfNgayHenTra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btXacNhan)
                                            .addComponent(btHuy)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(btTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btTaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btChon3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btDong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btXacNhan.setVisible(false);
        btHuy.setVisible(false);

        jPanel5.setBackground(new java.awt.Color(30, 29, 65));

        tbPhieuMuon.setBackground(new java.awt.Color(20, 20, 50));
        tbPhieuMuon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbPhieuMuon.setForeground(new java.awt.Color(255, 255, 255));
        tbPhieuMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Phiểu Mượn", "Mã Đọc Giả", "Mã Nhân Viên", "Ngày Mượn", "Ngày Hẹn Trả"
            }
        ));
        tbPhieuMuon.setGridColor(new java.awt.Color(255, 255, 255));
        tbPhieuMuon.setRowHeight(30);
        jScrollPane2.setViewportView(tbPhieuMuon);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBackground(new java.awt.Color(30, 29, 65));

        jPanel7.setBackground(new java.awt.Color(30, 29, 65));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mã Phiếu Mượn: ");

        tfMaPmChiTiet.setBackground(new java.awt.Color(27, 26, 67));
        tfMaPmChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        tfMaPmChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaPmChiTietActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mã Sách:");

        tfMaSach.setBackground(new java.awt.Color(27, 26, 67));
        tfMaSach.setForeground(new java.awt.Color(255, 255, 255));
        tfMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaSachActionPerformed(evt);
            }
        });

        btMaSach.setBackground(new java.awt.Color(27, 26, 67));
        btMaSach.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMaSach.setForeground(new java.awt.Color(255, 255, 255));
        btMaSach.setText("...");
        btMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaSachActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Số Lượng:");

        tfSoLuong.setBackground(new java.awt.Color(27, 26, 67));
        tfSoLuong.setForeground(new java.awt.Color(255, 255, 255));
        tfSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoLuongActionPerformed(evt);
            }
        });

        btThem1.setBackground(new java.awt.Color(27, 26, 67));
        btThem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThem1.setForeground(new java.awt.Color(255, 255, 255));
        btThem1.setText("Thêm");
        btThem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThem1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThem1ActionPerformed(evt);
            }
        });

        btXoa1.setBackground(new java.awt.Color(27, 26, 67));
        btXoa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoa1.setForeground(new java.awt.Color(255, 255, 255));
        btXoa1.setText("Xoá");
        btXoa1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoa1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoa1ActionPerformed(evt);
            }
        });

        btSua1.setBackground(new java.awt.Color(27, 26, 67));
        btSua1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSua1.setForeground(new java.awt.Color(255, 255, 255));
        btSua1.setText("Sửa");
        btSua1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSua1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSua1ActionPerformed(evt);
            }
        });

        btTaoMoi1.setBackground(new java.awt.Color(255, 153, 51));
        btTaoMoi1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTaoMoi1.setForeground(new java.awt.Color(255, 255, 255));
        btTaoMoi1.setText("Tạo mới");
        btTaoMoi1.setToolTipText("");
        btTaoMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTaoMoi1ActionPerformed(evt);
            }
        });

        btTimCt.setBackground(new java.awt.Color(27, 26, 67));
        btTimCt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimCt.setForeground(new java.awt.Color(255, 255, 255));
        btTimCt.setText("Tìm");
        btTimCt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimCtActionPerformed(evt);
            }
        });

        btAll.setBackground(new java.awt.Color(27, 26, 67));
        btAll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAll.setForeground(new java.awt.Color(255, 255, 255));
        btAll.setText("All");
        btAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAllActionPerformed(evt);
            }
        });

        btChon4.setBackground(new java.awt.Color(27, 26, 67));
        btChon4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btChon4.setForeground(new java.awt.Color(255, 255, 255));
        btChon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/select.png"))); // NOI18N
        btChon4.setText("Chọn");
        btChon4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btChon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChon4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(tfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMaSach))
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btXoa1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(btSua1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btChon4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMaPmChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btTaoMoi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btTimCt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(btAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaPmChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTimCt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMaSach))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAll))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btChon4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btTaoMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(30, 29, 65));

        tbChitiet.setBackground(new java.awt.Color(20, 20, 50));
        tbChitiet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbChitiet.setForeground(new java.awt.Color(255, 255, 255));
        tbChitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Phiếu Nhập", "Mã Sách", "Số Lượng"
            }
        ));
        tbChitiet.setGridColor(new java.awt.Color(255, 255, 255));
        tbChitiet.setPreferredSize(new java.awt.Dimension(375, 400));
        tbChitiet.setRowHeight(25);
        jScrollPane1.setViewportView(tbChitiet);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 234, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfMaPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaPhieuMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaPhieuMuonActionPerformed

    private void tfMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaDocGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaDocGiaActionPerformed

    private void tfMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaNhanVienActionPerformed

    private void tfNgayMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNgayMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNgayMuonActionPerformed

    private void tfNgayHenTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNgayHenTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNgayHenTraActionPerformed

    private void btMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaDocGiaActionPerformed
        // TODO add your handling code here:
        MaDocGiaSelector MaDGSel=new  MaDocGiaSelector();
        try {
            MaDGSel.List();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
        MaDGSel.setVisible(true);
    }//GEN-LAST:event_btMaDocGiaActionPerformed

    private void btMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaNhanVienActionPerformed
        // TODO add your handling code here:
        MaNhanVienSelector MaNVSel=new  MaNhanVienSelector();
        try {
            MaNVSel.List();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
        MaNVSel.setVisible(true);
    }//GEN-LAST:event_btMaNhanVienActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        // if(!ValidateThemPhieuMuon())
            //return;
       
        PhieuMuonDTO phieumuon=new PhieuMuonDTO();
        
        phieumuon.setMaPhieuMuon(tfMaPhieuMuon.getText());
        phieumuon.setMaDocGia(tfMaDocGia.getText());
        phieumuon.setMaNhanVien(tfMaNhanVien.getText());
        phieumuon.setNgayMuon(tfNgayMuon.getText());
        phieumuon.setNgayHenTra(tfNgayHenTra.getText());
        
        try {
            phieumuonbus.Add(phieumuon);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector row=new Vector();
        row.add(phieumuon.getMaPhieuMuon());
        row.add(phieumuon.getMaDocGia());
        row.add(phieumuon.getMaNhanVien());
        row.add(phieumuon.getNgayMuon());
        row.add(phieumuon.getNgayHenTra());
        
        modelPhieuMuon.addRow(row);
        
        tbPhieuMuon.setModel(modelPhieuMuon);
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        int i = tbPhieuMuon.getSelectedRow();
        if(phieumuonbus.getList().size()>0){
            try {
                phieumuonbus.Remove(phieumuonbus.getList().get(i).getMaPhieuMuon());
            } catch (Exception ex) {
                Logger.getLogger(QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
            }
            modelPhieuMuon.removeRow(i);
            tbPhieuMuon.setModel(modelPhieuMuon);
            
            tfMaPhieuMuon.setText("");
            tfMaDocGia.setText("");
            tfMaNhanVien.setText("");
            tfNgayMuon.setText("");
            tfNgayHenTra.setText("");
        }

    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        int i = tbPhieuMuon.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Chọn phiếu mượn cần chỉnh sửa", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        EditOrSearch=1;
        tfMaPhieuMuon.setEditable(false);
        tbPhieuMuon.setEnabled(false);
        btThem.setEnabled(false);
        btXoa.setEnabled(false);
        btTim.setEnabled(false);
        btTatCa.setEnabled(false);
        btXacNhan.setVisible(true);
        btHuy.setVisible(true);        // TODO add your handling code here:

    }//GEN-LAST:event_btSuaActionPerformed

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
        // TODO add your handling code here:
         EditOrSearch=0;
        btXacNhan.setText("Tìm");
        btXacNhan.setVisible(true);
        btHuy.setVisible(true);
    }//GEN-LAST:event_btTimActionPerformed

    private void btTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTatCaActionPerformed
        if (phieumuonbus.getList().size()>0)
            tbPhieuMuon.setModel(modelPhieuMuon);
    }//GEN-LAST:event_btTatCaActionPerformed

    private void btTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaoMoiActionPerformed
        if(tbPhieuMuon.isEnabled())
            tfMaPhieuMuon.setText("");
        /*if(EditOrSearch==0){
            tf.setText("");
            txSoLuongMax.setText("");
            txDonGiaMax.setText("");
        }*/
        tfMaDocGia.setText("");
        tfMaNhanVien.setText("");
        tfNgayMuon.setText("");
        tfNgayHenTra.setText("");
    }//GEN-LAST:event_btTaoMoiActionPerformed

    private void btXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXacNhanActionPerformed
        if(EditOrSearch==1){       
            Edit();
        }
        else{       
            Search();
        }
    }//GEN-LAST:event_btXacNhanActionPerformed

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
         if(EditOrSearch==1){
            tfMaPhieuMuon.setEditable(true);
            tbPhieuMuon.setEnabled(true);
            btThem.setEnabled(true);
            btXoa.setEnabled(true);
            btTim.setEnabled(true);
            btTatCa.setEnabled(true);
            //btNhapEx.setEnabled(true);
            //btXuatEx.setEnabled(true);
            btXacNhan.setVisible(false);
            btHuy.setVisible(false);
        }
        else{
            btXacNhan.setVisible(false);
            btHuy.setVisible(false); 
        }
    }//GEN-LAST:event_btHuyActionPerformed

    private void tfMaPmChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaPmChiTietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaPmChiTietActionPerformed

    private void tfMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaSachActionPerformed

    private void btMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaSachActionPerformed
        // TODO add your handling code here:
        MaSachSelector MaSachSel=new  MaSachSelector();
        try {
            MaSachSel.List();
        } catch (Exception ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }
        MaSachSel.setVisible(true);
    }//GEN-LAST:event_btMaSachActionPerformed

    private void tfSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoLuongActionPerformed

    private void btThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThem1ActionPerformed
        // TODO add your handling code here:
        ChiTietPhieuMuonDTO ctphieumuon=new ChiTietPhieuMuonDTO();
        
        ctphieumuon.setMaPhieuMuon(tfMaPmChiTiet.getText());
        ctphieumuon.setMaSach(tfMaSach.getText());
        ctphieumuon.setSoLuong(Integer.parseInt(tfSoLuong.getText()));
        
        try {
            chitietbus.Add(ctphieumuon);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector row=new Vector();
        row.add(ctphieumuon.getMaPhieuMuon());
        row.add(ctphieumuon.getMaSach());
        row.add(ctphieumuon.getSoLuong());
        
        modelChitiet.addRow(row);
        
        tbChitiet.setModel(modelChitiet);
    }//GEN-LAST:event_btThem1ActionPerformed

    private void btXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoa1ActionPerformed
        // TODO add your handling code here:
        int i = tbChitiet.getSelectedRow();
        if(chitietbus.getList().size()>0){
            try {
                chitietbus.Remove(chitietbus.getList().get(i).getMaPhieuMuon(), 
                                                    chitietbus.getList().get(i).getMaSach(), 
                                                    chitietbus.getList().get(i).getSoLuong());
            } catch (Exception ex) {
                Logger.getLogger(QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
            }
            modelChitiet.removeRow(i);
            tbChitiet.setModel(modelChitiet);
            
            tfMaPmChiTiet.setText("");
            tfMaSach.setText("");
            tfSoLuong.setText("");
        }
    }//GEN-LAST:event_btXoa1ActionPerformed

    private void btSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSua1ActionPerformed
        // TODO add your handling code here:
        int i = tbChitiet.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Chọn chi tiết phiếu mượn cần chỉnh sửa", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else EditCt();
    }//GEN-LAST:event_btSua1ActionPerformed

    private void btTaoMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTaoMoi1ActionPerformed
        // TODO add your handling code here:
        if(tbChitiet.isEnabled())
            tfMaPmChiTiet.setText("");
        /*if(EditOrSearch==0){
            tf.setText("");
            txSoLuongMax.setText("");
            txDonGiaMax.setText("");
        }*/
        tfMaSach.setText("");
        tfSoLuong.setText("");
    }//GEN-LAST:event_btTaoMoi1ActionPerformed

    private void btTimCtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimCtActionPerformed
         Searchct();
    }//GEN-LAST:event_btTimCtActionPerformed

    private void btAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAllActionPerformed
        // TODO add your handling code here:
         if (chitietbus.getList().size()>0)
            tbChitiet.setModel(modelChitiet);
    }//GEN-LAST:event_btAllActionPerformed

    private void btDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btDongActionPerformed

    private void btChon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChon3ActionPerformed
        // TODO add your handling code here:
        int i=tbPhieuMuon.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Chưa chọn mã hóa đơn", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try{
            QuanLyPhieuPhat.setMaPhieuMuon(phieumuonbus.getList().get(i).getMaPhieuMuon());
        }
        catch (Exception ex){
            System.out.println(ex);
        }
        this.dispose();
    }//GEN-LAST:event_btChon3ActionPerformed

    private void btChon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChon4ActionPerformed
        // TODO add your handling code here:
         int i=tbChitiet.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Chưa chọn mã sách", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }   
        try{
            QuanLyPhieuPhat.setMaSach(chitietbus.getList().get(i).getMaSach());
        }
        catch (Exception ex){
            System.out.println(ex);
        }
        this.dispose();
    }//GEN-LAST:event_btChon4ActionPerformed

    public void ListPhieuMuon() throws Exception{
        if(phieumuonbus.getList()==null)
             phieumuonbus.listPhieuMuon();
        ArrayList<PhieuMuonDTO> listPhieuMuon = phieumuonbus.getList();
        Vector header=new Vector();
        header.add("Mã Phiếu Mượn");
        header.add("Mã Đọc Giả");
        header.add("Mã Nhân Viên");
        header.add("Ngày Mượn");
        header.add("Ngày Hẹn Trả");
        if(modelPhieuMuon.getRowCount() == 0)
                modelPhieuMuon = new DefaultTableModel(header, 0);
        for(PhieuMuonDTO ctphieumuon: listPhieuMuon) {
            Vector row=new Vector();
            row.add(ctphieumuon.getMaPhieuMuon());
            row.add(ctphieumuon.getMaDocGia());
            row.add(ctphieumuon.getMaNhanVien());
            row.add(ctphieumuon.getNgayMuon());
            row.add(ctphieumuon.getNgayHenTra());
            modelPhieuMuon.addRow(row);
        }
        tbPhieuMuon.setModel(modelPhieuMuon);
    }
    public void ListChiTiet() throws Exception{
        if(chitietbus.getList()==null)
            chitietbus.listChiTietPhieuMuon();
        ArrayList<ChiTietPhieuMuonDTO> listChiTiet = chitietbus.getList();
        Vector header = new Vector();
        header.add("Mã Phiếu Nhập");
        header.add("Mã Sách");
        header.add("Số Lượng");
        if(modelChitiet.getRowCount() == 0)
            modelChitiet = new DefaultTableModel(header, 0);
        for(ChiTietPhieuMuonDTO chitiet: listChiTiet){
            Vector row=new Vector();
            row.add(chitiet.getMaPhieuMuon());
            row.add(chitiet.getMaSach());
            row.add(chitiet.getSoLuong());
            modelChitiet.addRow(row);
        }
        tbChitiet.setModel(modelChitiet);
    }
    private void Onclick() {
        int i = tbPhieuMuon.getSelectedRow();
        if (phieumuonbus.getList().size() > 0) {
            PhieuMuonDTO ctphieumuon = new PhieuMuonDTO();
            ctphieumuon = phieumuonbus.getList().get(i);
            
           tfMaPhieuMuon.setText(ctphieumuon.getMaPhieuMuon());
           tfMaNhanVien.setText(ctphieumuon.getMaNhanVien());
           tfMaDocGia.setText(ctphieumuon.getMaDocGia());
           tfNgayMuon.setText(ctphieumuon.getNgayMuon());
           tfNgayHenTra.setText(ctphieumuon.getNgayHenTra());
           tfMaPmChiTiet.setText(ctphieumuon.getMaPhieuMuon());
        }
    }
    private void Onclickct() {
        int ict = tbChitiet.getSelectedRow();
        if(chitietbus.getList().size()>0){
            ChiTietPhieuMuonDTO chitiet =new ChiTietPhieuMuonDTO();
            chitiet = chitietbus.getList().get(ict);
            
            tfMaPmChiTiet.setText(chitiet.getMaPhieuMuon());
            tfMaSach.setText(chitiet.getMaSach());
            tfSoLuong.setText(String.valueOf(chitiet.getSoLuong()));
        }
    }
    private void Edit(){
        int i=tbPhieuMuon.getSelectedRow();
        if(phieumuonbus.getList().size()>0){
            PhieuMuonDTO phieumuon=new PhieuMuonDTO();

            phieumuon.setMaPhieuMuon(tfMaPhieuMuon.getText());
            phieumuon.setMaDocGia(tfMaDocGia.getText());
            phieumuon.setMaNhanVien(tfMaNhanVien.getText());
            phieumuon.setNgayMuon(tfNgayMuon.getText());
            phieumuon.setNgayHenTra(tfNgayHenTra.getText());
            
            try {
                phieumuonbus.Edit(phieumuon);
            } catch (Exception ex) {
                Logger.getLogger(QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
            }

            modelPhieuMuon.setValueAt(phieumuon.getMaPhieuMuon(), i, 0);
            modelPhieuMuon.setValueAt(phieumuon.getMaDocGia(), i, 1);
            modelPhieuMuon.setValueAt(phieumuon.getMaNhanVien(), i, 2);
            modelPhieuMuon.setValueAt(phieumuon.getNgayMuon(), i, 3);
            modelPhieuMuon.setValueAt(phieumuon.getNgayHenTra(), i, 4);

            tbPhieuMuon.setModel(modelPhieuMuon);
        }
        tfMaPhieuMuon.setEditable(true);
        tbPhieuMuon.setEnabled(true);
        btThem.setEnabled(true);
        btXoa.setEnabled(true);
        btTim.setEnabled(true);
        btTatCa.setEnabled(true);
        //btNhapEx.setEnabled(true);
        //btXuatEx.setEnabled(true);
        btXacNhan.setVisible(false);
        btHuy.setVisible(false);
    }
    private void EditCt(){
        int i=tbChitiet.getSelectedRow();
        if(chitietbus.getList().size()>0){
           ChiTietPhieuMuonDTO ctphieumuon=new ChiTietPhieuMuonDTO();

            ctphieumuon.setMaPhieuMuon(tfMaPmChiTiet.getText());
            ctphieumuon.setMaSach(tfMaSach.getText());
            ctphieumuon.setSoLuong(Integer.parseInt(tfSoLuong.getText()));
            
            try {
                chitietbus.Edit(ctphieumuon);
            } catch (Exception ex) {
                Logger.getLogger(QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
            }

            modelChitiet.setValueAt(ctphieumuon.getMaPhieuMuon(), i, 0);
            modelChitiet.setValueAt(ctphieumuon.getMaSach(), i, 1);
            modelChitiet.setValueAt(ctphieumuon.getSoLuong(), i, 2);

            tbChitiet.setModel(modelChitiet);
        }
    }
    
    private void Search(){
        if(phieumuonbus.getList().isEmpty()){
            return;
        }

        String MaPhieuMuon, MaDocGia, MaNhanVien, NgayMuon, NgayHenTra;

        MaPhieuMuon=tfMaPhieuMuon.getText();
        MaDocGia=tfMaDocGia.getText();
        MaNhanVien=tfMaNhanVien.getText();
        NgayMuon=tfNgayMuon.getText();
         NgayHenTra=tfNgayHenTra.getText();

        ArrayList<PhieuMuonDTO> res=new ArrayList<PhieuMuonDTO>();
        try {
            res=phieumuonbus.Search(MaPhieuMuon, MaDocGia, MaNhanVien, NgayMuon, NgayHenTra);
        } catch (Exception ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (res.size()==0)
            JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả nào!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        else{
            Vector header = new Vector();
            header.add("Mã Phiếu Mượn");
            header.add("Mã Đọc Giả");
            header.add("Mã Nhân Viên");
            header.add("Ngày Nhập");
            header.add("Ngày Hẹn Trả");
            resOfSearch = new DefaultTableModel(header, 0);
            for(PhieuMuonDTO s: res){
                Vector row=new Vector();
                row.add(s.getMaPhieuMuon());
                row.add(s.getMaDocGia());
                row.add(s.getMaNhanVien());
                row.add(s.getNgayMuon());
                row.add(s.getNgayHenTra());
                resOfSearch.addRow(row);
            }
            tbPhieuMuon.setModel(resOfSearch);
        }
    }
    private void Searchct(){
        if(chitietbus.getList().isEmpty()){
            return;
        }

        String MaPhieuMuon, MaSach;
        int SoLuong;

        MaPhieuMuon=tfMaPmChiTiet.getText();
        MaSach=tfMaSach.getText();
        if(tfSoLuong.getText().equals(""))
            SoLuong=-1;
        else
            SoLuong=Integer.parseInt(tfSoLuong.getText());

        ArrayList<ChiTietPhieuMuonDTO> res=new ArrayList<ChiTietPhieuMuonDTO>();
        try {
            res=chitietbus.Search(MaPhieuMuon, MaSach, SoLuong);
        } catch (Exception ex) {
            Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (res.size()==0)
            JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả nào!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        else{
            Vector header = new Vector();
            header.add("Mã Phiếu Mượn");
            header.add("Mã Sách");
            header.add("Số Lượng");
            resOfSearch = new DefaultTableModel(header, 0);
            for(ChiTietPhieuMuonDTO s: res){
                Vector row=new Vector();
                row.add(s.getMaPhieuMuon());
                row.add(s.getMaSach());
                row.add(s.getSoLuong());
                resOfSearch.addRow(row);
            }
            tbChitiet.setModel(resOfSearch);
        }
    }
      public static  void setMaSach(String MaSach){
                tfMaSach.setText(MaSach);
    }
      public static  void setMaNV(String MaNV){
                tfMaNhanVien.setText(MaNV);
    }
      public static  void setMaDG(String MaDG){
                tfMaDocGia.setText(MaDG);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyMuonTra QLMT = new QuanLyMuonTra();
                try {
                    QLMT.ListPhieuMuon();
                    QLMT.ListChiTiet();
                } catch (Exception ex) {
                    Logger.getLogger(QuanLySach.class.getName()).log(Level.SEVERE, null, ex);
                }
                QLMT.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAll;
    private javax.swing.JButton btChon3;
    private javax.swing.JButton btChon4;
    private javax.swing.JButton btDong;
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btMaDocGia;
    private javax.swing.JButton btMaNhanVien;
    private javax.swing.JButton btMaSach;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btSua1;
    private javax.swing.JButton btTaoMoi;
    private javax.swing.JButton btTaoMoi1;
    private javax.swing.JButton btTatCa;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThem1;
    private javax.swing.JButton btTim;
    private javax.swing.JButton btTimCt;
    private javax.swing.JButton btXacNhan;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btXoa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbChitiet;
    private javax.swing.JTable tbPhieuMuon;
    private static javax.swing.JTextField tfMaDocGia;
    private static javax.swing.JTextField tfMaNhanVien;
    private javax.swing.JTextField tfMaPhieuMuon;
    private static javax.swing.JTextField tfMaPmChiTiet;
    private static javax.swing.JTextField tfMaSach;
    private javax.swing.JTextField tfNgayHenTra;
    private javax.swing.JTextField tfNgayMuon;
    private javax.swing.JTextField tfSoLuong;
    // End of variables declaration//GEN-END:variables
}
