/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.PhieuPhatBUS;
import BUS.ChiTietPhieuPhatBUS;
import DTO.PhieuPhatDTO;
import DTO.ChiTietPhieuPhatDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author Lộc
 */
public class QuanLyPhieuPhat extends javax.swing.JFrame {
    
    private DefaultTableModel modelPhieuPhat = new DefaultTableModel();
    private DefaultTableModel modelChitiet = new DefaultTableModel();
    private DefaultTableModel resOfSearch;
    private int EditOrSearch;
    private String position;
    private PhieuPhatBUS phieuphatbus=new PhieuPhatBUS();
    private ChiTietPhieuPhatBUS chitietbus=new ChiTietPhieuPhatBUS();
    
    /**
     * Creates new form DanhMuc
     */
    public QuanLyPhieuPhat() {
        initComponents();
        tbchitietpp.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent me) {

            }

            @Override
            public void mousePressed(MouseEvent me) {
                onclickct();
            }

            @Override
            public void mouseReleased(MouseEvent me) {

            }

            @Override
            public void mouseEntered(MouseEvent me) {

            }

            @Override
            public void mouseExited(MouseEvent me) {

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formTheLoai = new RoundedPanel(50, new Color(20, 20, 50));
        jLabel2 = new javax.swing.JLabel();
        txMaPP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txMaPM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbphieuphat = new javax.swing.JTable();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btTim = new javax.swing.JButton();
        jPanel2 = new RoundedPanel(10, new Color(68, 187, 236));
        jLabel1 = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();
        btAll = new javax.swing.JButton();
        btxacnhan = new javax.swing.JButton();
        btHuy = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txTongTien = new javax.swing.JTextField();
        btmapm = new javax.swing.JButton();
        formTacGia = new RoundedPanel(50, new Color(20, 20, 50));
        jLabel4 = new javax.swing.JLabel();
        txMactpp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txmasach = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbchitietpp = new javax.swing.JTable();
        btThemCT = new javax.swing.JButton();
        btSuaCT = new javax.swing.JButton();
        btXoaCT = new javax.swing.JButton();
        btTimCT = new javax.swing.JButton();
        jPanel3 = new RoundedPanel(10, new Color(68, 187, 236));
        jLabel6 = new javax.swing.JLabel();
        btClearCT = new javax.swing.JButton();
        btAllCT = new javax.swing.JButton();
        btxacnhanct = new javax.swing.JButton();
        btHuyCT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txmaloi = new javax.swing.JTextField();
        btmasach = new javax.swing.JButton();
        btmalp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(43, 10));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(30, 29, 65));

        formTheLoai.setBackground(new java.awt.Color(30, 29, 65));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã phiếu phạt:");

        txMaPP.setBackground(new java.awt.Color(27, 26, 67));
        txMaPP.setForeground(new java.awt.Color(255, 255, 255));
        txMaPP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txMaPPKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã Phiếu mượn:");

        txMaPM.setBackground(new java.awt.Color(27, 26, 67));
        txMaPM.setForeground(new java.awt.Color(255, 255, 255));

        tbphieuphat.setBackground(new java.awt.Color(27, 26, 67));
        tbphieuphat.setForeground(new java.awt.Color(255, 255, 255));
        tbphieuphat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã phiếu phạt", "Mã phiếu mượn", "Tổng Tiền Phạt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbphieuphat.setGridColor(new java.awt.Color(255, 255, 255));
        tbphieuphat.setRowHeight(18);
        tbphieuphat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbphieuphatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbphieuphat);

        btThem.setBackground(new java.awt.Color(27, 26, 67));
        btThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThem.setForeground(new java.awt.Color(255, 255, 255));
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/add.png"))); // NOI18N
        btThem.setText("Thêm");
        btThem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setBackground(new java.awt.Color(27, 26, 67));
        btSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSua.setForeground(new java.awt.Color(255, 255, 255));
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/edit.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setBackground(new java.awt.Color(27, 26, 67));
        btXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoa.setForeground(new java.awt.Color(255, 255, 255));
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/minus.png"))); // NOI18N
        btXoa.setText("Xoá");
        btXoa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btTim.setBackground(new java.awt.Color(27, 26, 67));
        btTim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTim.setForeground(new java.awt.Color(255, 255, 255));
        btTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/search.png"))); // NOI18N
        btTim.setText("Tìm");
        btTim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTim.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(20, 20, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHIẾU PHẠT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btClear.setBackground(new java.awt.Color(255, 153, 51));
        btClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btClear.setForeground(new java.awt.Color(255, 255, 255));
        btClear.setText("Tạo mới");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });

        btAll.setBackground(new java.awt.Color(165, 201, 63));
        btAll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAll.setForeground(new java.awt.Color(255, 255, 255));
        btAll.setText("Tất cả");
        btAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAllActionPerformed(evt);
            }
        });

        btxacnhan.setBackground(new java.awt.Color(165, 201, 63));
        btxacnhan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btxacnhan.setForeground(new java.awt.Color(255, 255, 255));
        btxacnhan.setText("Xác nhận");
        btxacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxacnhanActionPerformed(evt);
            }
        });

        btHuy.setBackground(new java.awt.Color(206, 81, 80));
        btHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btHuy.setForeground(new java.awt.Color(255, 255, 255));
        btHuy.setText("Huỷ");
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tổng tiền phạt:");

        txTongTien.setBackground(new java.awt.Color(27, 26, 67));
        txTongTien.setForeground(new java.awt.Color(255, 255, 255));
        txTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTongTienActionPerformed(evt);
            }
        });

        btmapm.setText("...");
        btmapm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmapmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formTheLoaiLayout = new javax.swing.GroupLayout(formTheLoai);
        formTheLoai.setLayout(formTheLoaiLayout);
        formTheLoaiLayout.setHorizontalGroup(
            formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTheLoaiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(formTheLoaiLayout.createSequentialGroup()
                        .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(formTheLoaiLayout.createSequentialGroup()
                                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(25, 25, 25)
                                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txMaPP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(formTheLoaiLayout.createSequentialGroup()
                                            .addComponent(txMaPM)
                                            .addGap(25, 25, 25)
                                            .addComponent(btmapm))
                                        .addComponent(txTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(formTheLoaiLayout.createSequentialGroup()
                                .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btAll, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
        );
        formTheLoaiLayout.setVerticalGroup(
            formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTheLoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txMaPP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txMaPM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btmapm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btTim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btxacnhan.setVisible(false);
        btHuy.setVisible(false);

        formTacGia.setBackground(new java.awt.Color(30, 29, 65));
        formTacGia.setPreferredSize(new java.awt.Dimension(556, 408));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã phiếu phạt:");

        txMactpp.setBackground(new java.awt.Color(27, 26, 67));
        txMactpp.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã sách:");

        txmasach.setBackground(new java.awt.Color(27, 26, 67));
        txmasach.setForeground(new java.awt.Color(255, 255, 255));

        tbchitietpp.setBackground(new java.awt.Color(27, 26, 67));
        tbchitietpp.setForeground(new java.awt.Color(255, 255, 255));
        tbchitietpp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã phiếu phạt", "Mã sách", "Mã lỗi phạt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbchitietpp.setGridColor(new java.awt.Color(255, 255, 255));
        tbchitietpp.setRowHeight(18);
        jScrollPane2.setViewportView(tbchitietpp);

        btThemCT.setBackground(new java.awt.Color(27, 26, 67));
        btThemCT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemCT.setForeground(new java.awt.Color(255, 255, 255));
        btThemCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/add.png"))); // NOI18N
        btThemCT.setText("Thêm");
        btThemCT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThemCT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btThemCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemCTActionPerformed(evt);
            }
        });

        btSuaCT.setBackground(new java.awt.Color(27, 26, 67));
        btSuaCT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSuaCT.setForeground(new java.awt.Color(255, 255, 255));
        btSuaCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/edit.png"))); // NOI18N
        btSuaCT.setText("Sửa");
        btSuaCT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSuaCT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btSuaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaCTActionPerformed(evt);
            }
        });

        btXoaCT.setBackground(new java.awt.Color(27, 26, 67));
        btXoaCT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoaCT.setForeground(new java.awt.Color(255, 255, 255));
        btXoaCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/minus.png"))); // NOI18N
        btXoaCT.setText("Xoá");
        btXoaCT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoaCT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btXoaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaCTActionPerformed(evt);
            }
        });

        btTimCT.setBackground(new java.awt.Color(27, 26, 67));
        btTimCT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimCT.setForeground(new java.awt.Color(255, 255, 255));
        btTimCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/search.png"))); // NOI18N
        btTimCT.setText("Tìm");
        btTimCT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTimCT.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btTimCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimCTActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(20, 20, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CHI TIẾT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        btClearCT.setBackground(new java.awt.Color(255, 153, 51));
        btClearCT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btClearCT.setForeground(new java.awt.Color(255, 255, 255));
        btClearCT.setText("Tạo mới");
        btClearCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearCTActionPerformed(evt);
            }
        });

        btAllCT.setBackground(new java.awt.Color(165, 201, 63));
        btAllCT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAllCT.setForeground(new java.awt.Color(255, 255, 255));
        btAllCT.setText("Tất cả");
        btAllCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAllCTActionPerformed(evt);
            }
        });

        btxacnhanct.setBackground(new java.awt.Color(165, 201, 63));
        btxacnhanct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btxacnhanct.setForeground(new java.awt.Color(255, 255, 255));
        btxacnhanct.setText("Xác nhận");
        btxacnhanct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxacnhanctActionPerformed(evt);
            }
        });

        btHuyCT.setBackground(new java.awt.Color(206, 81, 80));
        btHuyCT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btHuyCT.setForeground(new java.awt.Color(255, 255, 255));
        btHuyCT.setText("Huỷ");
        btHuyCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyCTActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mã lỗi phạt:");

        txmaloi.setBackground(new java.awt.Color(27, 26, 67));
        txmaloi.setForeground(new java.awt.Color(255, 255, 255));

        btmasach.setText("...");
        btmasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmasachActionPerformed(evt);
            }
        });

        btmalp.setText("...");
        btmalp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmalpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formTacGiaLayout = new javax.swing.GroupLayout(formTacGia);
        formTacGia.setLayout(formTacGiaLayout);
        formTacGiaLayout.setHorizontalGroup(
            formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formTacGiaLayout.createSequentialGroup()
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formTacGiaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(formTacGiaLayout.createSequentialGroup()
                        .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formTacGiaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(formTacGiaLayout.createSequentialGroup()
                                        .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(29, 29, 29)
                                        .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txMactpp, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(formTacGiaLayout.createSequentialGroup()
                                                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txmaloi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                                    .addComponent(txmasach, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(30, 30, 30)
                                                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btmasach)
                                                    .addComponent(btmalp)))))
                                    .addGroup(formTacGiaLayout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(btAllCT, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(btxacnhanct, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(formTacGiaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(formTacGiaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btClearCT, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btThemCT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuaCT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXoaCT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btTimCT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btHuyCT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
        );
        formTacGiaLayout.setVerticalGroup(
            formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTacGiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThemCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txMactpp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSuaCT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txmasach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btXoaCT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btmasach)))
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formTacGiaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTimCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formTacGiaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txmaloi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btmalp))
                        .addGap(18, 18, 18)))
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btClearCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAllCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHuyCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btxacnhanct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btxacnhanct.setVisible(false);
        btHuyCT.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(formTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 27, Short.MAX_VALUE)
                .addComponent(formTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbphieuphatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbphieuphatMouseClicked
        // TODO add your handling code here:
        int i = tbphieuphat.getSelectedRow();
        if (phieuphatbus.getList().size() > 0) {
            PhieuPhatDTO phieuphat= new PhieuPhatDTO();
            phieuphat = phieuphatbus.getList().get(i);
           
            txMaPP.setText(phieuphat.getMaPhieuPhat());
            txMactpp.setText(phieuphat.getMaPhieuPhat());
            txMaPM.setText(phieuphat.getMaPhieuMuon());
            txTongTien.setText(String.valueOf(phieuphat.getTongTien()));
            
        }
    }//GEN-LAST:event_tbphieuphatMouseClicked
    private void onclickct() {                                         
        // TODO add your handling code here:
        int i = tbchitietpp.getSelectedRow();
        if (chitietbus.getList().size() > 0) {
            ChiTietPhieuPhatDTO ctphieuphat= new ChiTietPhieuPhatDTO();
            ctphieuphat = chitietbus.getList().get(i);
           
            txMactpp.setText(ctphieuphat.getMaPhieuPhat());
            txmasach.setText(ctphieuphat.getMaSach());
            txmaloi.setText(ctphieuphat.getMaLoiPhat());
            
        }
    }                                        
    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
         if(tbphieuphat.isEnabled())
            txMaPM.setText("");
        /*if(EditOrSearch==0){
            tf.setText("");
            txSoLuongMax.setText("");
            txDonGiaMax.setText("");
        }*/
        txMaPM.setText("");
        txTongTien.setText("");
    }//GEN-LAST:event_btClearActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        position="phieuphat";
        if(!validateBtThem())
            return;
        
        PhieuPhatDTO phieuphat=new PhieuPhatDTO();
        
        phieuphat.setMaPhieuPhat(txMaPP.getText());
        phieuphat.setMaPhieuMuon(txMaPM.getText());
        phieuphat.setTongTien(Integer.parseInt(txTongTien.getText()));
        
        try {
            phieuphatbus.Add(phieuphat);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector row=new Vector();
        row.add(phieuphat.getMaPhieuPhat());
        row.add(phieuphat.getMaPhieuMuon());
        row.add(phieuphat.getTongTien());
        
        modelPhieuPhat.addRow(row);
        
        tbphieuphat.setModel(modelPhieuPhat);
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
         int i = tbphieuphat.getSelectedRow();
        if(phieuphatbus.getList().size()>0){
            try {
                phieuphatbus.Remove(phieuphatbus.getList().get(i).getMaPhieuPhat());
            } catch (Exception ex) {
                Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(Level.SEVERE, null, ex);
            }
            modelPhieuPhat.removeRow(i);
            tbphieuphat.setModel(modelPhieuPhat);
            
            txMaPP.setText("");
            txMaPM.setText("");
            txTongTien.setText("");
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int i=tbphieuphat.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Chọn thể loại cần chỉnh sửa", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        txMaPP.setEditable(false);
        btxacnhan.setVisible(true);
        btHuy.setVisible(true);
        btThem.setEnabled(false);
        btXoa.setEnabled(false);
        btTim.setEnabled(false);
        btAll.setEnabled(false);
        tbphieuphat.setEnabled(false);
    }//GEN-LAST:event_btSuaActionPerformed

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        // TODO add your handling code here:
        txMaPP.setEditable(true);
        btxacnhan.setVisible(false);
        btHuy.setVisible(false);
        btThem.setEnabled(true);
        btXoa.setEnabled(true);
        btTim.setEnabled(true);
        btAll.setEnabled(true);
        tbphieuphat.setEnabled(true);
    }//GEN-LAST:event_btHuyActionPerformed

    private void txMaPPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txMaPPKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            txMaPM.requestFocus();
    }//GEN-LAST:event_txMaPPKeyPressed

    private void btxacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxacnhanActionPerformed
        // TODO add your handling code here:
        int i=tbphieuphat.getSelectedRow();
        if(phieuphatbus.getList().size()>0){
            PhieuPhatDTO phieuphat=new PhieuPhatDTO();

            phieuphat.setMaPhieuPhat(txMaPP.getText());
            phieuphat.setMaPhieuMuon(txMaPM.getText());
            phieuphat.setTongTien(Integer.parseInt(txTongTien.getText()));

            try {
                phieuphatbus.Edit(phieuphat);
            } catch (Exception ex) {
                Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(Level.SEVERE, null, ex);
            }

            modelPhieuPhat.setValueAt(phieuphat.getMaPhieuPhat(), i, 0);
            modelPhieuPhat.setValueAt(phieuphat.getMaPhieuMuon(), i, 1);
            modelPhieuPhat.setValueAt(phieuphat.getTongTien(), i, 2);
            

            tbphieuphat.setModel(modelPhieuPhat);
        }
  
    }//GEN-LAST:event_btxacnhanActionPerformed

    private void btAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAllActionPerformed
        // TODO add your handling code here:
        if (phieuphatbus.getList().size()>0)
            tbphieuphat.setModel(modelPhieuPhat);
    }//GEN-LAST:event_btAllActionPerformed

    private void btTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimActionPerformed
        // TODO add your handling code here:
        if(phieuphatbus.getList().isEmpty()){
            return;
        }

        String MaPP, MaPM;
        int TongTien;


        MaPP=txMaPP.getText();
        MaPM=txMaPM.getText();
        if(txTongTien.getText().equals("")){
            TongTien=-1;
        }else TongTien=Integer.parseInt(txTongTien.getText());
        
        ArrayList<PhieuPhatDTO> res=new ArrayList<PhieuPhatDTO>();
        try {
            res=phieuphatbus.Search(MaPP, MaPM, TongTien);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (res.size()==0)
            JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả nào!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        else{
            Vector header = new Vector();
            header.add("Mã  phiếu phạt");
            header.add("Mã phiếu mượn");
            header.add("Tổng tiền phạt");
            
            resOfSearch = new DefaultTableModel(header, 0);
            for(PhieuPhatDTO tl: res){
                Vector row=new Vector();
                row.add(tl.getMaPhieuPhat());
                row.add(tl.getMaPhieuMuon());
                row.add(tl.getTongTien());
                resOfSearch.addRow(row);
            }
            tbphieuphat.setModel(resOfSearch);
        }
    }//GEN-LAST:event_btTimActionPerformed

    private void txTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTongTienActionPerformed

    private void btmapmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmapmActionPerformed
        // TODO add your handling code here:
        QuanLyMuonTra qlmt=new  QuanLyMuonTra();
        try {
            qlmt.ListPhieuMuon();
            qlmt.ListChiTiet();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
        qlmt.setVisible(true);
    }//GEN-LAST:event_btmapmActionPerformed

    private void btmalpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmalpActionPerformed
        // TODO add your handling code here:
        DanhSachQuyDinh dsqd=new  DanhSachQuyDinh();
        try {
            dsqd.List();
        } catch (Exception ex) {
            Logger.getLogger(QuanLyMuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
        dsqd.setVisible(true);
    }//GEN-LAST:event_btmalpActionPerformed

    private void btmasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmasachActionPerformed
        // TODO add your handling code here:
        QuanLyMuonTra qlmt=new  QuanLyMuonTra();
        try {
            qlmt.ListPhieuMuon();
            qlmt.ListChiTiet();
        } catch (Exception ex) {
            Logger.getLogger(MaSachSelector.class.getName()).log(Level.SEVERE, null, ex);
        }
        qlmt.setVisible(true);
    }//GEN-LAST:event_btmasachActionPerformed

    private void btThemCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemCTActionPerformed
        // TODO add your handling code here:
        position="chitietphieuphat";
        if(!validateBtThem())
            return;
        
        ChiTietPhieuPhatDTO ctphieuphat=new ChiTietPhieuPhatDTO();
        
        ctphieuphat.setMaPhieuPhat(txMactpp.getText());
        ctphieuphat.setMaSach(txmasach.getText());
        ctphieuphat.setMaLoiPhat(txmaloi.getText());
        
        try {
            chitietbus.Add(ctphieuphat);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Vector row=new Vector();
        row.add(ctphieuphat.getMaPhieuPhat());
        row.add(ctphieuphat.getMaSach());
        row.add(ctphieuphat.getMaLoiPhat());
        
        modelChitiet.addRow(row);
        
        tbchitietpp.setModel(modelChitiet);
    }//GEN-LAST:event_btThemCTActionPerformed

    private void btSuaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaCTActionPerformed
        // TODO add your handling code here:
         int i=tbchitietpp.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Chọn chi tiết lỗicần chỉnh sửa", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        txMactpp.setEditable(false);
        btxacnhanct.setVisible(true);
        btHuyCT.setVisible(true);
        btThemCT.setEnabled(false);
        btXoaCT.setEnabled(false);
        btTimCT.setEnabled(false);
        btAllCT.setEnabled(false);
        tbchitietpp.setEnabled(false);
    }//GEN-LAST:event_btSuaCTActionPerformed

    private void btxacnhanctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxacnhanctActionPerformed
        // TODO add your handling code here:
        int i=tbchitietpp.getSelectedRow();
        if(chitietbus.getList().size()>0){
            ChiTietPhieuPhatDTO ctphieuphat=new ChiTietPhieuPhatDTO();

            ctphieuphat.setMaPhieuPhat(txMactpp.getText());
            ctphieuphat.setMaSach(txmasach.getText());
            ctphieuphat.setMaLoiPhat(txmaloi.getText());

            try {
                chitietbus.Edit(ctphieuphat);
            } catch (Exception ex) {
                Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(Level.SEVERE, null, ex);
            }

            modelChitiet.setValueAt(ctphieuphat.getMaPhieuPhat(), i, 0);
            modelChitiet.setValueAt(ctphieuphat.getMaSach(), i, 1);
            modelChitiet.setValueAt(ctphieuphat.getMaLoiPhat(), i, 2);
            

            tbchitietpp.setModel(modelChitiet);
        }
  
    }//GEN-LAST:event_btxacnhanctActionPerformed

    private void btHuyCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyCTActionPerformed
        // TODO add your handling code here:
        txMactpp.setEditable(true);
        btxacnhanct.setVisible(false);
        btHuyCT.setVisible(false);
        btThemCT.setEnabled(true);
        btXoaCT.setEnabled(true);
        btTimCT.setEnabled(true);
        btAllCT.setEnabled(true);
        tbchitietpp.setEnabled(true);
    }//GEN-LAST:event_btHuyCTActionPerformed

    private void btXoaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaCTActionPerformed
        // TODO add your handling code here:
         int i = tbchitietpp.getSelectedRow();
        if(chitietbus.getList().size()>0){
            try {
                chitietbus.Remove(chitietbus.getList().get(i).getMaPhieuPhat(),
                                                   chitietbus.getList().get(i).getMaSach(),
                                                   chitietbus.getList().get(i).getMaLoiPhat());
            } catch (Exception ex) {
                Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(Level.SEVERE, null, ex);
            }
            modelChitiet.removeRow(i);
            tbchitietpp.setModel(modelChitiet);
            
            txMactpp.setText("");
            txmasach.setText("");
            txmaloi.setText("");
        }
    }//GEN-LAST:event_btXoaCTActionPerformed

    private void btTimCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimCTActionPerformed
        // TODO add your handling code here:
        if(chitietbus.getList().isEmpty()){
            return;
        }

        String MaPP, MaSach, MaLP;


        MaPP=txMactpp.getText();
        MaSach=txmasach.getText();
        MaLP=txmaloi.getText();
        
        ArrayList<ChiTietPhieuPhatDTO> res=new ArrayList<ChiTietPhieuPhatDTO>();
        try {
            res=chitietbus.Search(MaPP, MaSach, MaLP);
        } catch (Exception ex) {
            Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (res.size()==0)
            JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả nào!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        else{
            Vector header = new Vector();
            header.add("Mã  phiếu phạt");
            header.add("Mã sách");
            header.add("Mã lỗi phạt");
            
            resOfSearch = new DefaultTableModel(header, 0);
            for(ChiTietPhieuPhatDTO tl: res){
                Vector row=new Vector();
                row.add(tl.getMaPhieuPhat());
                row.add(tl.getMaSach());
                row.add(tl.getMaLoiPhat());
                resOfSearch.addRow(row);
            }
            tbchitietpp.setModel(resOfSearch);
        }
    }//GEN-LAST:event_btTimCTActionPerformed

    private void btAllCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAllCTActionPerformed
        // TODO add your handling code here:
         if (chitietbus.getList().size()>0)
            tbchitietpp.setModel(modelChitiet);
    }//GEN-LAST:event_btAllCTActionPerformed

    private void btClearCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearCTActionPerformed
        // TODO add your handling code here:
        if(tbchitietpp.isEnabled())
            txMactpp.setText("");
        /*if(EditOrSearch==0){
            tf.setText("");
            txSoLuongMax.setText("");
            txDonGiaMax.setText("");
        }*/
        txmasach.setText("");
        txmaloi.setText("");
    }//GEN-LAST:event_btClearCTActionPerformed
    
    private boolean validateBtThem(){
        switch(position){
            case "phieuphat":
                String MaPP, MaPM;
                int TongTien;
                MaPP=txMaPP.getText();
                MaPM=txMaPM.getText();
                TongTien=Integer.parseInt(txTongTien.getText());
                if(MaPP.equals("") || MaPM.equals("") || TongTien==-1){
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
                    return false;
                }
                for(PhieuPhatDTO phieuphat: phieuphatbus.getList()){
                    if(MaPP.equals(phieuphat.getMaPhieuPhat())){
                        JOptionPane.showMessageDialog(null, "Mã phiếu phạt đã tồn tại", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
                        return false;
                    }
                }
                break;
            case "chitietphieuphat":
                String MaPhieuPhat, MaSach,MaLP;
                MaPhieuPhat=txMactpp.getText();
                MaSach=txmasach.getText();
                MaLP=txmaloi.getText();
                if(MaPhieuPhat.equals("") || MaSach.equals("") || MaLP.equals("")){
                    JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
                    return false;
                }
                break;
            
        }
        return true;
    }
    
    public void ListPhieuPhat() throws Exception{
        if(phieuphatbus.getList()==null)
            phieuphatbus.listPhieuPhat();
        ArrayList<PhieuPhatDTO> listPP = phieuphatbus.getList();
        Vector header=new Vector();
        header.add("Mã phiếu phạt");
        header.add("Mã phiếu mượn");
        header.add("Tổng tiền phạt");
        if (modelPhieuPhat.getRowCount() == 0) 
                modelPhieuPhat= new DefaultTableModel(header, 0);
        for(PhieuPhatDTO phieuphat: listPP) {
            Vector row=new Vector();
            row.add(phieuphat.getMaPhieuPhat());
            row.add(phieuphat.getMaPhieuMuon());
            row.add(phieuphat.getTongTien());
            modelPhieuPhat.addRow(row);
        }
        tbphieuphat.setModel(modelPhieuPhat);
    }
    public void ListCTPhieuPhat() throws Exception{
        if(chitietbus.getList()==null)
            chitietbus.listChiTietPhieuPhat();
        ArrayList<ChiTietPhieuPhatDTO> listCTPP = chitietbus.getList();
        Vector header=new Vector();
        header.add("Mã phiếu phạt");
        header.add("Mã sách");
        header.add("Mã lỗi phạt");
        if (modelChitiet.getRowCount() == 0) 
                modelChitiet= new DefaultTableModel(header, 0);
        for(ChiTietPhieuPhatDTO phieuphat: listCTPP) {
            Vector row=new Vector();
            row.add(phieuphat.getMaPhieuPhat());
            row.add(phieuphat.getMaSach());
            row.add(phieuphat.getMaLoiPhat());
            modelChitiet.addRow(row);
        }
        tbchitietpp.setModel(modelChitiet);
    }
    
    public static  void setMaSach(String MaSach){
                txmasach.setText(MaSach);
    }
    public static  void setMaPhieuMuon(String MaPhieuMuon){
                txMaPM.setText(MaPhieuMuon);
    }
    public static  void setMaLoiPhat(String MaLoiPhat){
                txmaloi.setText(MaLoiPhat);
    }
    private boolean ValidateThem(){
        String mapp, mapm, tong;
        mapp=txMaPP.getText();
        mapm=txMaPM.getText();
        tong=txTongTien.getText();
        if(mapp.equals("") || mapm.equals("") || tong.equals("")){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ thông tin", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        for(PhieuPhatDTO pp: phieuphatbus.getList()){
            if(mapp.equals(pp.getMaPhieuPhat())){
                JOptionPane.showMessageDialog(null, "Mã độc giả đã tồn tại", "Chú ý!", JOptionPane.INFORMATION_MESSAGE);
                return false;
            }
        }     
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyPhieuPhat phieuphat=new QuanLyPhieuPhat();
                try {
                    phieuphat.ListPhieuPhat();
                    phieuphat.ListCTPhieuPhat();
                } catch (Exception ex) {
                    Logger.getLogger(QuanLyPhieuPhat.class.getName()).log(Level.SEVERE, null, ex);
                }
                phieuphat.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAll;
    private javax.swing.JButton btAllCT;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btClearCT;
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btHuyCT;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btSuaCT;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThemCT;
    private javax.swing.JButton btTim;
    private javax.swing.JButton btTimCT;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btXoaCT;
    private javax.swing.JButton btmalp;
    private javax.swing.JButton btmapm;
    private javax.swing.JButton btmasach;
    private javax.swing.JButton btxacnhan;
    private javax.swing.JButton btxacnhanct;
    private javax.swing.JPanel formTacGia;
    private javax.swing.JPanel formTheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbchitietpp;
    private javax.swing.JTable tbphieuphat;
    private static javax.swing.JTextField txMaPM;
    private javax.swing.JTextField txMaPP;
    private javax.swing.JTextField txMactpp;
    private javax.swing.JTextField txTongTien;
    private static javax.swing.JTextField txmaloi;
    private static javax.swing.JTextField txmasach;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
